"use client";
import {FormEvent,useEffect,useState}from"react";import{Button}from"../components/Button";
type Stats={totalRequests:number;byType:{name:string;count:number}[];byCountry:{name:string;count:number}[];recent:unknown[][]};
export default function StatsPage(){const[stats,setStats]=useState<Stats|null>(null),[code,setCode]=useState(""),[sent,setSent]=useState(false),[error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/stats");if(r.ok)setStats(await r.json());};useEffect(()=>{void load();},[]);
 const send=async()=>{setError("");const r=await fetch("/api/stats/request-otp",{method:"POST"});if(r.ok)setSent(true);else setError((await r.json()).error);};
 const verify=async(e:FormEvent)=>{e.preventDefault();const r=await fetch("/api/stats/verify-otp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});if(r.ok)await load();else setError((await r.json()).error);};
 if(!stats)return <main className="grid min-h-[calc(100vh-4rem)] place-items-center bg-[#E2E1DF] p-5 dark:bg-[#0C3B2E]"><form onSubmit={verify} className="w-full max-w-md rounded-3xl bg-white p-8 dark:bg-[#173F35]"><h1 className="text-2xl font-semibold dark:text-white">Statistics access</h1><p className="mt-2 text-sm text-slate-500">Request a one-time code sent to the configured administrator email.</p>{sent&&<input value={code}onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,8))}placeholder="8-digit code"className="mt-5 w-full rounded-xl border p-3"/>}{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}{sent?<Button className="mt-4 w-full justify-center">Verify code</Button>:<Button type="button"onClick={send}className="mt-5 w-full justify-center">Email me a code</Button>}</form></main>;
 return <main className="min-h-screen bg-[#E2E1DF] p-8 dark:bg-[#0C3B2E]"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-semibold dark:text-white">Server statistics</h1><div className="mt-6 grid gap-4 md:grid-cols-3"><Card title="Actual API requests"value={stats.totalRequests}/><Card title="Countries"value={stats.byCountry.length}/><Card title="Request types"value={stats.byType.length}/></div><div className="mt-6 overflow-auto rounded-2xl bg-white p-5 dark:bg-[#173F35]"><table className="w-full text-left text-sm dark:text-white"><thead><tr>{["Time","IP","Country","Method","Path","Type","Status","ms","Tenant"].map(h=><th key={h}className="p-2">{h}</th>)}</tr></thead><tbody>{stats.recent.map((row,i)=><tr key={i}className="border-t">{row.map((cell,j)=><td key={j}className="whitespace-nowrap p-2">{String(cell??"—")}</td>)}</tr>)}</tbody></table></div></div></main>;}
function Card({title,value}:{title:string;value:number}){return <div className="rounded-2xl bg-white p-5 dark:bg-[#173F35]"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-3xl font-semibold dark:text-white">{value}</p></div>}
