import { CodeXml, FileImage, Files, FileType2, FolderCog, ListOrdered, Lock, LockOpen, Minimize2, Scissors, Stamp } from "lucide-react";

export const cardConfig = [
  {
    title: "Directory workflow",
    content: "Convert, compress and merge supported files from an entire folder.",
    link: "/workflows",
    Icon: FolderCog,
    available: true,
  },
  {
    title: "JPEG to PDF",
    content: "Turn one or more JPG, JPEG or PNG images into a polished PDF.",
    link: "/jpeg-to-pdf",
    Icon: FileImage,
    available: true,
  },
  {
    title: "Merge PDF",
    content: "Combine multiple PDF documents into one organized file.",
    link: "/merge-pdf",
    Icon: Files,
    available: true,
  },
  {
    title: "Compress PDF",
    content: "Reduce PDF file size while keeping documents clear and readable.",
    link: "/compress-pdf",
    Icon: Minimize2,
    available: true,
  },
  {
    title: "Add page numbers",
    content: "Add clear, sequential page numbers to any PDF document.",
    link: "/page-numbers",
    Icon: ListOrdered,
    available: true,
  },
  {
    title: "HTML to PDF",
    content: "Turn HTML and CSS into a polished, print-ready PDF document.",
    link: "/html-to-pdf",
    Icon: CodeXml,
    available: true,
  },
  {
    title: "RTF to PDF",
    content: "Convert formatted RTF documents into polished, shareable PDFs.",
    link: "/rtf-to-pdf",
    Icon: FileType2,
    available: true,
  },
  {
    title: "Split PDF",
    content: "Separate one page or a whole set into independent PDF files.",
    link: "/split-pdf",
    Icon: Scissors,
    available: true,
  },
  {
    title: "Protect PDF",
    content: "Add password protection to one PDF or a merged collection.",
    link: "/protect-pdf",
    Icon: Lock,
    available: true,
  },
  {
    title: "Unlock PDF",
    content: "Remove password protection from a PDF you are authorized to access.",
    link: "/unlock-pdf",
    Icon: LockOpen,
    available: true,
  },
  {
    title: "Watermark PDF",
    content: "Add a custom text watermark to every page of a PDF document.",
    link: "/watermark-pdf",
    Icon: Stamp,
    available: true,
  },
];
